### ISSUE TITLE
您好关于聊天内容里面有一对多的实体要如何保存历史记录

### ISSUE THREAD

**Issue by yuekong** [Maxi-Mao/ChatDemo#10]
*/
    @Id(autoincrement = true)
    private Long id;
    private String chatType = "chatRoom";
    private Long e_id;
    @ToOne(joinProperty = "e_id")
    private ExtBean ext;

**Comment by maximilianMao** [comment]
你是要做聊天室吧，我觉得前端的话可以通过登陆的用户id和其后台传的聊天室id绑定存储。
