### ISSUE TITLE
RecyclerView消息界面，有图片信息滚动到底部的时候，会出现两条信息重叠的情况

### ISSUE THREAD

**Issue by tracy891110** [Maxi-Mao/ChatDemo#11]
RecyclerView消息界面，有图片信息滚动到底部的时候，会出现两条信息重叠的情况

**Comment by maximilianMao** [comment]
信息重叠？是不是因为图片大小不固定导致item高度不固定导致的？要不你试试把图片的高度也存到数据库，然后每次item如果是图片的话就将高度固定成比图片高度稍大点？

**Comment by tracy891110** [comment]
![device-2017-07-14-170618](https://user-images.githubusercontent.com/5525150/28865304-fbca2b7a-77a1-11e7-8a4f-de9ce4e9c086.png)

你是说加载图片的时候直接把大小固定起来？
这个是上下滚动到底部的时候会出现这样的问题。。。。

**Comment by maximilianMao** [comment]
嗯，我猜测是因为图片大小不固定导致的，可以试着将item按内容大小固定其高度。如果没有图片只有文字和语音的情况下，如果不出现这种重叠现象，那基本可以确定是因为图片是动态的高度问题导致的了。

**Comment by tracy891110** [comment]
嗯， 好的，谢谢，我去试试

**Comment by maximilianMao** [comment]
添加占位图应该也可以解决
