### ISSUE TITLE
下拉加载更多时，未等提示的textview归位快速再次下拉会导致textview无法正常归位

### ISSUE THREAD

**Issue by wayne-law** [Maxi-Mao/ChatDemo#13]
就是onViewReleased中那个归位的动画效果还没完成就再次下拉  就会导致下拉加载的提示头无法隐藏

**Comment by maximilianMao** [comment]
行，有时间我看看，下拉加载更多这块如果不好用的话可以用一些市场上比较成熟的控件替换，都可以的

**Comment by maximilianMao** [comment]
我试了几下没有复现不清楚是什么情况，可以加群详细说说 qq群：135451435
