### ISSUE TITLE
您好，请教您一个动画的问题

### ISSUE THREAD

**Issue by Valor2** [Maxi-Mao/ChatDemo#16]
我是拿了您的聊天项目，结果我弄过去后发现发送文本消息的时候文字会上下跳动下，上下翻动历史记录的时候 文字会重叠，能帮忙解答下嘛

**Comment by maximilianMao** [comment]
我想你应该是用了recyclerview吧 这里面rv我记得notify的时候没有使用局部刷新 也就是你如果新发送文本的时候需要制定position进行刷新了。上下翻动文字重叠不清楚，不过我估计是图文混排 播放表情gif帧的时候 里的handler造成的，可以修改一下，或者做一下取舍。

**Comment by Valor2** [comment]
您好我做了取舍，去掉了以下代码，但是发现本人发送文字的时候，先显示文字闪一下白，在显示出来，我还在继续排查
  myList.setItemAnimator(new SlideInOutBottomItemAnimator(myList));

**Comment by maximilianMao** [comment]
这个是rv的动画。我猜测应该是GifTextView的问题，你可以把这个替换成Textview试试

**Comment by Valor2** [comment]
我把gifTextView替换了，没用。闪动的时候就是在消息列表没有数据白板的时候 闪，一但消息发送到列表底部后就不删了，网上说notifyiteminserted 插入的有闪动，但是没找到具体啥问题，找了几个取消动画的 结果还是一样闪
