### ISSUE TITLE
收到的语音消息下载策略

### ISSUE THREAD

**Issue by Gaara33** [Maxi-Mao/ChatDemo#5]
收到的语音消息怎么来维护下载策略呢,比如聊天界面每次加载50条数据,有30条是收到的语音消息,那么怎么做到只有在屏幕中显示的语音消息才开始下载并更新界面?

**Comment by maximilianMao** [comment]
关于语音下载这块，我也考虑过，因为语音的特性与图片不同，图片是直接显示，及时性高，而语音则是点击才播放，显示出来的只是相应的长短而已，及时性相对低，所以内存缓存可以忽略掉，但是考虑到节省流量的问题，肯定是要缓存到本地的，所以可以点击后边播边存，如果考虑到网络状态差所造成的延时问题，那么可以在收到语音后便下载到本地。结合这两方面，我觉得下载策略应该是收到语音后下载到本地，用户点击后先去找本地有没有，如果没有则边下边存，如果有则播放本地。
