### ISSUE TITLE
请问一下RecyclerView键盘遮挡布局问题

### ISSUE THREAD

**Issue by coderluo** [Maxi-Mao/ChatDemo#6]
我使用了您的 controlKeyboardLayout 方法，但是在弹出键盘时还是会遮挡RecyclerView，您是怎么解决这个问题的呢？

**Comment by maximilianMao** [comment]
这块我的思路是 根据键盘高度确定 rv的滑动高度 如果rv内容较少 屏幕高度-内容高度<键盘高度 那就不滚动 如果 屏幕高度 - 内容高度 > 键盘高度 && 内容高度 < 屏幕高度 则rv滚动距离是 键盘高度 - （屏幕高度 - 内容高度） 如果 内容高度>=屏幕高度 那么rv滚动距离就是 键盘高度。如果还有问题 那应该是 某个高度获取有误差？就比如有的屏幕虚拟按键（这块我已经处理了），就是类似这种，如果还未解决可以具体说一下是什么问题。对了 或许是键盘高度获取有误差？你打个log看一下

**Comment by coderluo** [comment]
谢谢您如此细致的回答，我想问下，要实现这个效果我该使用您的项目里的哪些东西，

**Comment by maximilianMao** [comment]
其实就是搭配rv里的controlKeyboardLayout方法就可以了。
