### ISSUE TITLE
语音功能的BUG

### ISSUE THREAD

**Issue by angersad** [Maxi-Mao/ChatDemo#9]
在使用完语音功能之后,语音消息并不能及时的显示在界面上,甚至整个界面就直接卡死了.不是到时失去焦点了还是因为ANR...
造成这个的原因是因为网络原因还是音频的缓存机制的问题?求大神指导

**Comment by maximilianMao** [comment]
你调试一下看看输出的log信息，我也不请楚你说的问题，不知道是不是偶然情况，或者是不是因为机器的问题。你先调试一下，实在不行可以发一下调试信息log

**Comment by angersad** [comment]
换了台手机是解决这个问题了..但我又发现了一个新问题,在点击emoji表情弹出布局后发送的消息会被挡住.是否是你忘记考虑这方面了

**Comment by maximilianMao** [comment]
昂，对，这块我没做，因为当时就是写个demo，所以也没弄那么细，你可以参照键盘弹出修改。

**Comment by angersad** [comment]
好的,我最近做这个项目也是头疼的紧,还要在你的基础上加好几个Viewtype的视图,还好有看到你的库,省了很多事

**Comment by maximilianMao** [comment]
嗯嗯 很高兴能对你有帮助

**Comment by angersad** [comment]
今天抽了一下你的代码...不知道为什么
public class ChatDbManager extends BaseManager<ChatMessageBean,Long> {

    @Override
    public AbstractDao<ChatMessageBean, Long> getAbstractDao() {
        return daoSession.getChatMessageBeanDao();
    }
return 这一行会报空

**Comment by maximilianMao** [comment]
这是封装的GreenDAO数据库,记录聊天信息的
